// Generated by monorepo-scripts/generate-knip-config.mts
// Do not edit manually - regenerate with: pnpm generate:knip
import { defineKnipConfig } from "../../monorepo-scripts/knip-defaults.js";

export default defineKnipConfig({
    entry: ["src/index.ts"],
    project: ["src/**/*.ts"],
    ignoreDependencies: ["vitest", "@vitest/coverage-v8"],
    ignoreBinaries: ["tsup", "python3"],
    ignore: ["tsup.config.ts", "test/**"],
    includeEntryExports: true,
    rules: {
        exports: "off",
        duplicates: "off",
        types: "off",
    },
});
